### PR TITLE
fix compiling issues on linux

### PR DESCRIPTION
**Pull request by ghost**
- ensure `bin` directory to exist
- use `-lm` to use lib math in order to support `math.h`

### CODE REVIEW

**Comment by kbrsh** [comment]
Hey! I had some changes locally and just pushed them. For #4 and #5 could you pull the changes I made and edit the Makefile again?

**Comment by oltdaniel** [comment]
@kbrsh Updated with upstream

**Review by ghost — COMMENTED** [review]
@kbrsh ping

**Comment by ghost** [comment]
@kbrsh ping

**Pull request closed without merging**
